FROM golang:1.16 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN make build-mvm

FROM frolvlad/alpine-glibc:latest

WORKDIR /app

COPY --from=builder /app/builds/doracle-mvm .

EXPOSE 7121

ENTRYPOINT ["/app/doracle-mvm"]
